### ISSUE TITLE
Could not get to work

### ISSUE THREAD

**Issue by bradurani** [thalesmello/vim-textobj-methodcall#1]
I couldn't get this to work. I tried the defaults, the alternative mappings and my own alternative mappings and it I couldn't get it to select the method call.

I realize that's not very helpful, I'll try to investigate a bit more thoroughly if I get time.

**Comment by blueyed** [comment]
Which language/filetype are you using?
It seems to expect JavaScript style?!

**Comment by thalesmello** [comment]
This was developed with Javascript in mind, so languages like Java should work as is. It won't work if the language uses another type of dot, such as -> in C and C++, or the method call isn't surrounded by parenthesis, such as when you have do.. end blocks in Ruby.

It can easily be extended to support those, though.

**Comment by thalesmello** [comment]
@bradurani What language are you trying to use this with? Does the single method call shortcut (vim or vam) work?

Try to write `print('hi')` in an empty buffer, place the cursor at the beginning of the line and then type `vim` in normal mode. 

Does it select the method call?

**Comment by bradurani** [comment]
I was using it with Ruby, which is the same syntax. I'll try again tonight

**Comment by thalesmello** [comment]
@bradurani In ruby, this plugin would work as long as you always use parenthesis in method calls and do not use blocks in the chain.

Could you provide me with an example of code that you tried vim-textobj-methodcall with?

**Comment by thalesmello** [comment]
@bradurani I think the reason you weren't able to get mappings to work in ruby was because of the http://github.com/vim-ruby/vim-ruby. Take a look at this pull request that fixes the issue: https://github.com/vim-ruby/vim-ruby/pull/299

Plus, I've also started working on methodcall support for Ruby. I still have some work left to do, but I can select ruby blocks already.

**Comment by bradurani** [comment]
That fixed it! Thanks!
